services:
  - type: web
    name: odin-flight-booker
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh && ./bin/rails db:seed'
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: './bin/rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: odin-flight-booker-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false # You'll provide this value on Blueprint creation
      - key: WEB_CONCURRENCY
        value: 2 # Recommended default
databases:
  - name: odin-flight-booker-db
    plan: free
